### ISSUE TITLE
As an user, I would want to see a confirmation dialogue when user uses a snippet

### ISSUE THREAD

**Issue by neontvn** [cse210-fa24-group13/codesnip#23]
The existing implementation creates the snippet directly without asking for any confirmation from the user.
The team members used the extension extensively and ran into a situation where multiple snippet files got created. 

Analyze and implement the confirmation page in VSCode extension

**Comment by FudeCao** [comment]
What I proposed yesterday was adding a confirmation page when copying the existing snippets to the editor, but this is also a possible feature to add.

**Comment by Kshitijde** [comment]
Fude could you add a screenshot to this issue for better understanding and documenation

**Comment by FudeCao** [comment]
![Image](https://github.com/user-attachments/assets/70169efb-080b-40e7-a651-37a7a58e08eb)
![Image](https://github.com/user-attachments/assets/a4e75e12-0a50-45cc-904d-7b417198b57e)
1. The cursor is put on the editor.
2. Click on the snippet file on the left side
3. The code snippet is added to the cursor position.
So I want a confirmation page between 2 and 3 to avoid adding by accident, like avoiding deleting by accident.

**Comment by neontvn** [comment]
> What I proposed yesterday was adding a confirmation page when copying the existing snippets to the editor, but this is also a possible feature to add.

Understood your use case.

Thinking from a user perspective, will it not add more number of clicks to use a snippet? What do you think?

**Comment by FudeCao** [comment]
Yes, indeed that will cost one more click. But in the current extension, double-clicking on the snippet file would add the code snippet twice. I would say this is not a common protocol.

**Comment by neontvn** [comment]
Makes sense. Let's discuss this once with the team in the standup tomorrow.

**Comment by FudeCao** [comment]
[functionality documentation.pdf](https://github.com/user-attachments/files/17837076/functionality.documentation.pdf)
Please take a look at it. I am not sure if I have made my point clear.

**Comment by Kshitijde** [comment]
Let's go through it as a team today and decide on whether to take this up as a feature tmw

**Comment by FudeCao** [comment]
It is an easy implementation. I have done it and uploaded to Fude_Confirmation_Dialogue branch. It should work, at least on my side.
https://github.com/cse210-fa24-group13/codesnip/tree/Fude_Confirmation_Dialogue

**Comment by Kshitijde** [comment]
That's great, let us check this out live tomorrow and if all goes well, you could just raise a PR and we can merge this!

**Comment by neontvn** [comment]
Add test cases to the code written for this task
