### ISSUE TITLE
As a developer, understand how to recompile VSCode extension on local

### ISSUE THREAD

**Issue by neontvn** [cse210-fa24-group13/codesnip#26]

**Comment by Kshitijde** [comment]
Use VSIX file to compile and verify the changes made locally

**Comment by FudeCao** [comment]
I have tried this over the weekend. This is how I compile the extension
To ensure terminal has authorization to install script:

> Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

Install webpack

> npm install --save-dev webpack webpack-cli

Compile

> npm run compile

Then we could use Run and Debug on the left side to enter debug window
![Image](https://github.com/user-attachments/assets/4d3a3e2f-27e0-4b6b-ae83-cac97ea5515e)

To export a vsix file,
Install vsce

> npm install -g vsce

Package the extension using vsce

> vsce package

This will output a vsix file in the project folder
Then import vsix file in the extensions interface

**Comment by neontvn** [comment]
That's amazing @FudeCao ! If you already tried it out, I would request you to coordinate with @angusyick @ChrisChen0803 and explain to them as well how it works, probably over a call. 

Also, please create a document with all the steps and screenshots to do this. This can then be referred by others as well.

Thanks!

**Comment by neontvn** [comment]
If possible, try to close this task up "by today/tomorrow?" so that we get those extra 3 days till Saturday to take a look at other tasks. Thanks again

**Comment by neontvn** [comment]
Able to get it working.

**Comment by rohanthorat27** [comment]
@FudeCao amazing. I was struggling to compile modifications to the extension until I saw your tutorial.
