### ISSUE TITLE
ADR: Brownfield or Greenfield

### ISSUE THREAD

**Issue by neontvn** [cse210-fa24-group13/codesnip#3]

**Comment by Jyotikakakar** [comment]
[ADR_GreenfieldvsBrownfield.md](https://github.com/user-attachments/files/17708277/ADR_GreenfieldvsBrownfield.md)

**Comment by neontvn** [comment]
Folder structure in which we will maintain ADRs - /specs/adrs

**Comment by ChrisChen0803** [comment]
Updated. Create a branch and wait for reviews and approval to merge.

**Comment by ChrisChen0803** [comment]
Update adr problem statement, add table. Waiting for reviews and approval to merge.
