### ISSUE TITLE
Update dependencies to their latest versions

### ISSUE THREAD

**Issue by neontvn** [cse210-fa24-group13/codesnip#30]
Check the relevant dependencies in the project and update them to their latest version.

**Comment by Kshitijde** [comment]
Test: If the behavior stays consistent and there are no conflicts post dependencies being bumped

**Comment by YingJiehXia** [comment]
I created a new branch "Update_Dependencies", and updated the package.json using `ncu -u`.

**Comment by Kshitijde** [comment]
All check are not passing after upgrading the dependancies

**Comment by Kshitijde** [comment]
Closing this issue, PR has already been merged. The issue with the checks has been resolved
