### ISSUE TITLE
Create user interface, that allows me to see all the created snippets

### ISSUE THREAD

**Issue by neontvn** [cse210-fa24-group13/codesnip#36]
Web user interface that displays all the snippets

**Comment by Kshitijde** [comment]
Basic setup for UI and snippets rendering done.. connecting the two is pending

**Comment by Kshitijde** [comment]
We can create a checklist for this issue as this covers a broad spectrum of tasks..alternatively we could just create smaller more specific issues so that this is easier to track

**Comment by neontvn** [comment]
@rohanthorat27 @YingJiehXia you go through the changes @ChrisChen0803 has done from this branch: https://github.com/cse210-fa24-group13/codesnip/tree/Angus_Mokshita_Chris-WebUI

**Comment by rohanthorat27** [comment]
I was able to run it. I see he's added an extra button in the navigation bar to display the snippets in the extension itself.
![Screenshot (149)](https://github.com/user-attachments/assets/462daa39-ee72-4a6e-826f-89aa31613bd3)
