### ISSUE TITLE
GitHub GIST ADR

### ISSUE THREAD

**Issue by Kshitijde** [cse210-fa24-group13/codesnip#39]

**Comment by Jyotikakakar** [comment]
https://docs.google.com/document/d/17UAMZGeNN_H7JVeye3uEiITAGw1RyaAniilo8V9o-wc/edit?usp=sharing

can you guys please review this and provide feedback. Ill then change it to md.

**Comment by Kshitijde** [comment]
Could you add the table (https://github.com/cse210-fa24-group13/codesnip/blob/main/specs/adrs/01_code_coverage_tool.md) as done for the previous ADRs so that we keep it consistent?

Also do we consider version control during decision making right now? That is a feature which might not make sense and can be infeasible. So let's exclude that from consideration for now I feel. 

Apart from that the format structure and content looks good !

**Comment by Jyotikakakar** [comment]
Thank you for the feedback, Kshitij! Will make the changes.

**Comment by Jyotikakakar** [comment]
[Gist ADR.md](https://github.com/user-attachments/files/17911581/Gist.ADR.md)
