### ISSUE TITLE
Analyze Github Actions 

### ISSUE THREAD

**Issue by neontvn** [cse210-fa24-group13/codesnip#8]
- Try out Github Actions
- Document how we can use it for this project

**Comment by neontvn** [comment]
- Tested Actions using TypeDoc
- Aware of how this can be setup

**Comment by Kshitijde** [comment]
- Analyzed how github actions work, the basics of the commands and the structure.
- Setup a typedoc action to generate documentation every time there is a new push.
- Can work on more specific usecases that cater to our immediate needs during development. For eg. auto generating regression tests, deploying the website part of our system etc.

**Comment by Kshitijde** [comment]
Different  branches need to have different build setup/github actions setups
